version: '3.9'
services:
  web:
    container_name: pl-script-nest
    image: samagragovernance/nl-scripts:latest
    env_file:
      - .env
    command: yarn run start:prod
    ports:
      - '${PORT}:3000'
